version: '2'
services:
    couchbase:
        image: couchbase-custom
        ports:
            - 8097:8091
            - 8098:8092
            - 8099:8093
        environment:
            - COUCHBASE_ADMINISTRATOR_USERNAME=Admin
            - COUCHBASE_ADMINISTRATOR_PASSWORD=password
            - COUCHBASE_BUCKET=default
            - COUCHBASE_BUCKET_PASSWORD=
    userservice:
        image: ecommerce-userservice
        ports:
            - 5555:8805
        environment:
            - COUCHBASE_HOST=couchbase
            - COUCHBASE_BUCKET=default
        restart: always
    productservice:
        image: ecommerce-productservice
        ports:
            - 5556:8806
        environment:
            - COUCHBASE_HOST=couchbase
            - COUCHBASE_BUCKET=default
        restart: always
    nginx:
        image: nginx:latest
        ports:
            - "8080:8080"
        volumes:
            - ./web/public:/srv/www/static
            - ./default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - userservice
            - productservice